### ISSUE TITLE
Вариант 17. Вектор в трёхмерном пространстве

### ISSUE THREAD

**Issue by PylaevaSvetlana** [PylaevaSvetlana/TKI-141-2sem-#1]
![image](https://github.com/PylaevaSvetlana/TKI-141-2sem-/assets/144165563/4beee736-11f3-4736-ac2e-fcb90933adfb)

**Comment by MarinaPaley** [comment]
@PylaevaSvetlana Кажется, что данное задание не имеет смысла. Я не понимаю, что сама хотела, я его исправлю. Для класса Точка не надо складывать и вычитать с числом... Для Вектора, думаю, что нужно продумать параллельный перенос, если они не исходят или не входят в одну точку.
